version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: shop-db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shop_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
